"use strict"

#
#   all the tests stuff my dear old chap
#

FILE_NAME = 'test.coffee'

grunt = require "grunt"
report = require './report'
util = require './util'

_tests = {}

_executeTest = ( testname, variation, testOptions, file, taskOptions ) ->
  lineNumbers = file.findLineNumbers(testOptions.pattern)
  report.set(file, testname, taskOptions, lineNumbers)

#
# public methods
#

# register a test
# @param  string  key the key for this test
# @param  string  description describe the test
# @param  function  fn the test function
# @param  object|undefined  options the options for the test
registerTest = ( testName, test ) ->
  test.name = testName
#  grunt.log.debug 'Registered test ' + JSON.stringify(test)

# execute _tests on given file
# @param  object  file  fileObject generated by file.coffee
# @param  array|undefined _tests contains the _tests name to be executed of all if undefined
executeTests = ( file, options ) ->
  tests = options.tests
  for testName, test of tests
    registerTest(testName, test)
#    grunt.log.debug 'Found test ' + testName + ' with the parameters ' + JSON.stringify(test)
    _executeTest testName, false, test, file, options

# export the modules
module.exports =
  registerTest: registerTest
  executeTests: executeTests
  tests: _tests
